name: ChronoFlowFocusTimer
options:
  bundleIdPrefix: com.barkahnyadar
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    DEVELOPMENT_TEAM: G59B2KURRM
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: "1.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_FILE: Info.plist
    PRODUCT_NAME: ChronoFlowFocusTimer
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
targets:
  ChronoFlowFocusTimer:
    type: application
    platform: iOS
    sources:
      - path: ChronoFlowFocusTimer.swift
      - path: Models
      - path: ViewModels
      - path: Views
      - path: Services
      - path: Utils
    resources:
      - path: Resources/Assets.xcassets
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.barkahnyadar.chronoflow.focustimer
schemes:
  ChronoFlowFocusTimer:
    build:
      targets:
        ChronoFlowFocusTimer: all
